# Generated by Django 3.2.4 on 2021-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210703_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oridinal_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
