# Generated by Django 3.2.4 on 2021-07-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210704_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oridinal_bag',
            new_name='original_bag',
        ),
    ]
